import type { Metadata } from "next";
import localFont from 'next/font/local';
// @ts-ignore
import "./globals.css";

const abel = localFont({
  src: "./fonts/Abel.ttf",
  display: "swap",
  variable: "--font-abel",
})

const coolvetica = localFont({
  src: "./fonts/Coolvetica.otf",
  display: "swap",
  variable: "--font-coolvetica",
})

const monorama = localFont({
  src: "./fonts/Monorama.ttf",
  display: "swap",
  variable: "--font-monorama",
})

export const metadata: Metadata = {
  title: "Feynmind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body
        className={`${coolvetica.variable} ${monorama.variable} ${abel.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
